server:
  port: 8081

spring:
  application:
    name: order-service

  # Configuración de PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuración de Kafka
  kafka:
    bootstrap-servers: kafka-2470b0bd-pyamentsapp.e.aivencloud.com:22372
    properties:
      security.protocol: SSL
    ssl:
      trust-store-type: PEM
      trust-store-certificates: classpath:certs/ca.pem
      key-store-type: PEM
      key-store-certificate-chain: classpath:certs/service.cert
      key-store-key: classpath:certs/service.key

      # Configuración específica del Productor (ordersApp)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
