server:
  port: 8081

spring:
  application:
    name: order-service

  # Configuración de PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuración de Kafka
  kafka:
    bootstrap-servers: kafka-2470b0bd-pyamentsapp.e.aivencloud.com:22372
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="avnadmin" password="AVNS_BPOvkQfuJWIyIsPyxpU";
        ssl.endpoint.identification.algorithm: ""